name: Build and Deploy
on:
  push:
    branches:
      - web-src
  pull_request:
    branches:
      - web-src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/heads/web-src
          path: repo
      - name: Install prerequisites
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd repo
          npm install -g yarn
          yarn
      - name: Build
        run: |
          cd repo
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: repo/dist