name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  fetch_vpngate_list:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch list
        # HostName,IP,Score,Ping,Speed,CountryLong,CountryShort,NumVpnSessions,Uptime,TotalUsers,TotalTraffic,LogType,Operator,Message,OpenVPN_ConfigData_Base64
        run: |
          curl -s https://www.vpngate.net/api/iphone/ | \
          tail -n +3 | \
          while IFS="," read -r hostName ip score ping speed countryLong countryShort numVpnSessions uptime totalUsers totalTraffic logType operator message openVPN_ConfigData_Base64; do
            # Decode base64 to file
            echo "$openVPN_ConfigData_Base64" | tr -d "\r\n" | base64 -d > "$ip.ovpn"
          done
      - name: List files
        run: ls -l
