name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      vpngate-list: ${{ steps.fetch_list.outputs.vpngate_list }}
    steps:
      - id: fetch-list
        name: Fetch list
        run: |
          curl -s https://www.vpngate.net/api/iphone/ | \
          tail -n +3 | \
          while IFS="," read -r hostName ip score ping speed countryLong countryShort numVpnSessions uptime totalUsers totalTraffic logType operator message openVPN_ConfigData_Base64; do
            # Decode base64 to file
            echo "$openVPN_ConfigData_Base64" | tr -d "\r\n" | base64 -d > "$ip.ovpn"
          done
          echo "::set-output name=vpngate_list::$(ls *.ovpn)"
      - id: upload-list
        name: Upload list
        uses: actions/upload-artifact@v3
        with:
          name: vpngate-list
          path: '*.ovpn'
  dispatch:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      # - name: Download list
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: vpngate-list
      # - name: Test list
      #   run: |
      #     for file in *.ovpn; do
      #       echo "Testing $file"
      #     done
      - id: testing
        name: Testing
        run: echo ${{needs.prebuild.outputs.os}}